import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Header from '../../components/Haeder';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fast Reservation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="mx-auto border-b-[1px] rounded-lg h-20">
          <div
            className={`${inter.className} mx-auto w-innerWidth h-full flex items-center`}
          >
            <Header />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
